### ISSUE TITLE
random reboots under 18.1 release

### ISSUE THREAD

**Issue by masavini** [ItsVixano-releases/LineageOS_lisa#1]
hi,
i'm still using the latest 18.1 release and my device randomly reboots. sometimes it properly runs for days, some others it reboots twice in a few hours (like this morning).
is this a known issue? would updating to 19.1 release solve this issue?
thanks!

**Comment by ItsVixano** [comment]
18.1 is currently unmaintained
check if the issue persist with 19.1

**Comment by masavini** [comment]
thanks, i'll upgrade and send you a feedback.

**Comment by ItsVixano** [comment]
anything new regard this ??

**Comment by masavini** [comment]
hi,
sorry for the late reply.
the random reboots seemed to be gone in the last weeks but they have just started again.
i would upgrade to 19.1 this weekend, but i'm a little scared... if the upgrade goes horribly wrong will i be able to downgrade to 18.1?
thanks!

**Comment by masavini** [comment]
hi,
i upgraded to 19.1 a couple of weeks ago and since then the phone didn't reboot a single time.
i'm closing this issue, thank you very much for your work and your support.
